#!/bin/sh
#
#   /etc/init.d/ppp: start or stop PPP link.
#
# If you want PPP started on boot time (most dialup systems won't need it)
# rename the /etc/ppp/no_ppp_on_boot file to /etc/ppp/ppp_on_boot, and
# follow the instructions in the comments in that file.

# Source function library.
. /etc/init.d/functions

test -x /data/NeowayTest || exit 0

case "$1" in
  start)
      echo -n "Starting up ISTK"
      /data/NeowayTest --config=/data/neowayhelper.conf
    ;;
  stop)
      echo -n "Shutting down ISTK"
      killall NeowayTest
    ;;
  status)
    status /usr/sbin/pppd;
    exit $?
    ;;
  restart|force-reload)
    ;;
  *)
      echo "Usage: /etc/init.d/neoway {start|stop|status|restart|force-reload}"
      exit 1
    ;;
esac

exit 0
